Added support for V3
node-red/node-red-nodes pull request #705
Opened 2020-10-24 04:02 UTC by ASH3xC0d3

Added support for version 3.
All the existing issues with v1 and v2c are also with v3 e.g.
https://github.com/node-red/node-red-nodes/issues/679
snmp walker will not return more than 1000 objects, all following objects cannot be accessed
Incorrect encryption (privacy) passphrase gives a timeout and not an error (protocol limitation?)
Incorrect community string gives a timeout and not an error (protocol limitation?)
Changes to the node are made with following details:
Node-red v1.2.2
Node.js v12.6.0
Windows_NT 10.0.19841 x64 LE

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

## Checklist

- [ ] I have read the [contribution guidelines](https://github.com/node-red/node-red-nodes/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ ] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

2020-10-24 15:08 UTC, dceejay requested changes
So yes - two main things - 
1) is that we should hide any fields from the user that aren't necessary - so only show v3 relevant fields when v3 is selected. and keys when encryption is selected etc... A simple example to follow is in the smooth node 17-smooth.html line 35 and then 91, 96 . 
2) All credentials MUST be stored as credentials for security - so need to be handles as per docs - https://nodered.org/docs/creating-nodes/credentials - or for an example see the mysql node 68-mysql.html line 48 and 68-mysql.js line 39 and 97.

2020-10-24 15:08 UTC, dceejay commented on io/snmp/snmp.html
> +    <div class="form-row">
Likewise - do these need to be shown if "None" is selected above ?

2020-10-24 15:08 UTC, dceejay commented on io/snmp/snmp.html
> +    <div class="form-row">
Same again

2020-10-24 15:08 UTC, dceejay commented on io/snmp/snmp.html
> +            authkey: { value: "" },
Any credentials need to be handled as credentials and not general variables - see https://nodered.org/docs/creating-nodes/credentials (ie add a credential section like the defaults one but for the items that should be secret.)

2022-04-28 19:36 UTC, closed without merging

2022-04-28 19:38 UTC, Steve-Mcl commented
@ASH3xC0d3 your changes have been incorporated into an updated PR #904 and merged into master

Thanks for the PR 👍