Update pusher dependencies & code
node-red/node-red-nodes pull request #974
Opened 2023-02-01 14:26 UTC by shaqaruden

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Updates dependencies to latest available.

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red-nodes/blob/master/CONTRIBUTING.md)
- [ ] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ na ] I have added suitable unit tests to cover the new/changed functionality

2023-02-01 14:33 UTC, hardillb requested changes

2023-02-01 14:33 UTC, hardillb commented on social/pusher/package.json
> +        "url": "https://github.com/shaqaruden/node-red-nodes.git",
This should not be changed

2023-02-01 14:33 UTC, hardillb commented on social/pusher/package.json
> +        "email": "shaqaruden@gmail.com",
This should be a `contributors` section, not replacing existing author

https://docs.npmjs.com/cli/v9/configuring-npm/package-json#people-fields-author-contributors

2023-02-01 14:52 UTC, hardillb commented
Thanks for this, just a couple more points

What changed that required you to replace the icon? If pushers logo has changed please resize the new one to be match the size of the old one.

Also you will need to sign the CLA before we can accept the code. It should just be a case of clicking the link in the comment above

2023-02-01 15:10 UTC, shaqaruden commented
> What changed that required you to replace the icon? If pushers logo has changed please resize the new one to be match the size of the old one.

Pusher has a new logo, I will resize the icon to match the old one

2023-02-01 15:38 UTC, shaqaruden commented
> Thanks for this, just a couple more points
> 
> What changed that required you to replace the icon? If pushers logo has changed please resize the new one to be match the size of the old one.
> 
> Also you will need to sign the CLA before we can accept the code. It should just be a case of clicking the link in the comment above

All completed.

2023-02-02 09:59 UTC, hardillb approved these changes

2023-02-02 10:00 UTC, hardillb commented
@dceejay this looks good to me, please merge and push to npm when you can (might want to decide if we bump the version to 0.2.0/1.0.0 rather than 0.1.1)

2023-02-02 10:57 UTC, merged